CREATE TABLE `user` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE `table` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE SET NULL
);

CREATE TABLE `list` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position INT NOT NULL,  
  table_id INT NOT NULL,
  FOREIGN KEY (table_id) REFERENCES `table`(id) ON DELETE CASCADE
);

CREATE TABLE `card` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  position INT NOT NULL,
  list_id INT NOT NULL,
  FOREIGN KEY (list_id) REFERENCES `list`(id) ON DELETE CASCADE
);
ALTER TABLE list MODIFY COLUMN position INT NOT NULL DEFAULT 0;
ALTER TABLE card MODIFY COLUMN position INT NOT NULL DEFAULT 0;
